name: academia
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
    

  google_fonts : ^6.1.0
  material_color_utilities : ^0.11.0
  mask_text_input_formatter: ^2.4.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4

  cupertino_icons: ^1.0.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   
    - assets/carro.png

  
