// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8FysDzhn_yrVnKhp6_J5i_iEWUguYmBE',
    appId: '1:993754607160:android:c36c72dad7dd138cb400cd',
    messagingSenderId: '993754607160',
    projectId: 'rent-car-original',
    storageBucket: 'rent-car-original.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSTGhK9pQoboZMraWSZzcnmxzpWDgzc8',
    appId: '1:993754607160:ios:a2ad8a2e37b18bfbb400cd',
    messagingSenderId: '993754607160',
    projectId: 'rent-car-original',
    storageBucket: 'rent-car-original.firebasestorage.app',
    iosBundleId: 'com.example.academia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeQiw-yZec-0ZtJRMrvWOdMQIfj1kA7M4',
    appId: '1:993754607160:web:ebf42ec0487d4579b400cd',
    messagingSenderId: '993754607160',
    projectId: 'rent-car-original',
    authDomain: 'rent-car-original.firebaseapp.com',
    storageBucket: 'rent-car-original.firebasestorage.app',
    measurementId: 'G-172WXXDWRV',
  );
}
